#Documentation on services http://kubernetes.io/v1.1/docs/user-guide/services.html
#Details on exposing services http://kubernetes.io/v1.1/docs/user-guide/connecting-applications.html
apiVersion: v1
kind: Service
metadata:
  name: facebook-dataplug
  labels:
    app: facebook-dataplug
spec:
  selector:
    app: facebook-dataplug
  ports:
  - targetPort: 30080 #port on pod #nodePort: %port%
    port: 30080
    nodePort: 30080
    protocol: TCP
    name: http
  type: NodePort #this makes the ports accessible on the node
